/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedoutIndexRouteImport } from './routes/_loggedout/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as LoggedoutCoursesGenerateRoadmapIndexRouteImport } from './routes/_loggedout/courses/generate/roadmap/index'
import { Route as LoggedoutCoursesGenerateQuestionsIndexRouteImport } from './routes/_loggedout/courses/generate/questions/index'

const LoggedoutIndexRoute = LoggedoutIndexRouteImport.update({
  id: '/_loggedout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedoutCoursesGenerateRoadmapIndexRoute =
  LoggedoutCoursesGenerateRoadmapIndexRouteImport.update({
    id: '/_loggedout/courses/generate/roadmap/',
    path: '/courses/generate/roadmap/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoggedoutCoursesGenerateQuestionsIndexRoute =
  LoggedoutCoursesGenerateQuestionsIndexRouteImport.update({
    id: '/_loggedout/courses/generate/questions/',
    path: '/courses/generate/questions/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof LoggedoutIndexRoute
  '/courses/generate/questions': typeof LoggedoutCoursesGenerateQuestionsIndexRoute
  '/courses/generate/roadmap': typeof LoggedoutCoursesGenerateRoadmapIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof LoggedoutIndexRoute
  '/courses/generate/questions': typeof LoggedoutCoursesGenerateQuestionsIndexRoute
  '/courses/generate/roadmap': typeof LoggedoutCoursesGenerateRoadmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_loggedout/': typeof LoggedoutIndexRoute
  '/_loggedout/courses/generate/questions/': typeof LoggedoutCoursesGenerateQuestionsIndexRoute
  '/_loggedout/courses/generate/roadmap/': typeof LoggedoutCoursesGenerateRoadmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/'
    | '/courses/generate/questions'
    | '/courses/generate/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/courses/generate/questions'
    | '/courses/generate/roadmap'
  id:
    | '__root__'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_loggedout/'
    | '/_loggedout/courses/generate/questions/'
    | '/_loggedout/courses/generate/roadmap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  LoggedoutIndexRoute: typeof LoggedoutIndexRoute
  LoggedoutCoursesGenerateQuestionsIndexRoute: typeof LoggedoutCoursesGenerateQuestionsIndexRoute
  LoggedoutCoursesGenerateRoadmapIndexRoute: typeof LoggedoutCoursesGenerateRoadmapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_loggedout/': {
      id: '/_loggedout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LoggedoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_loggedout/courses/generate/roadmap/': {
      id: '/_loggedout/courses/generate/roadmap/'
      path: '/courses/generate/roadmap'
      fullPath: '/courses/generate/roadmap'
      preLoaderRoute: typeof LoggedoutCoursesGenerateRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_loggedout/courses/generate/questions/': {
      id: '/_loggedout/courses/generate/questions/'
      path: '/courses/generate/questions'
      fullPath: '/courses/generate/questions'
      preLoaderRoute: typeof LoggedoutCoursesGenerateQuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  LoggedoutIndexRoute: LoggedoutIndexRoute,
  LoggedoutCoursesGenerateQuestionsIndexRoute:
    LoggedoutCoursesGenerateQuestionsIndexRoute,
  LoggedoutCoursesGenerateRoadmapIndexRoute:
    LoggedoutCoursesGenerateRoadmapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
